package buquemu.community.mapper;

import buquemu.community.model.Praise;
import buquemu.community.model.PraiseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PraiseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated Sat Mar 14 21:40:41 CST 2020
     */
    long countByExample(PraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated Sat Mar 14 21:40:41 CST 2020
     */
    int deleteByExample(PraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated Sat Mar 14 21:40:41 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated Sat Mar 14 21:40:41 CST 2020
     */
    int insert(Praise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated Sat Mar 14 21:40:41 CST 2020
     */
    int insertSelective(Praise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated Sat Mar 14 21:40:41 CST 2020
     */
    List<Praise> selectByExampleWithRowbounds(PraiseExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated Sat Mar 14 21:40:41 CST 2020
     */
    List<Praise> selectByExample(PraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated Sat Mar 14 21:40:41 CST 2020
     */
    Praise selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated Sat Mar 14 21:40:41 CST 2020
     */
    int updateByExampleSelective(@Param("record") Praise record, @Param("example") PraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated Sat Mar 14 21:40:41 CST 2020
     */
    int updateByExample(@Param("record") Praise record, @Param("example") PraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated Sat Mar 14 21:40:41 CST 2020
     */
    int updateByPrimaryKeySelective(Praise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated Sat Mar 14 21:40:41 CST 2020
     */
    int updateByPrimaryKey(Praise record);
}