package buquemu.community.model;

public class Notice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.id
     *
     * @mbg.generated Sun Mar 08 20:59:38 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.notofier
     *
     * @mbg.generated Sun Mar 08 20:59:38 CST 2020
     */
    private Integer notofier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.receiver
     *
     * @mbg.generated Sun Mar 08 20:59:38 CST 2020
     */
    private Integer receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.type
     *
     * @mbg.generated Sun Mar 08 20:59:38 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.outerId
     *
     * @mbg.generated Sun Mar 08 20:59:38 CST 2020
     */
    private Integer outerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.gmt_create
     *
     * @mbg.generated Sun Mar 08 20:59:38 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.status
     *
     * @mbg.generated Sun Mar 08 20:59:38 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.title
     *
     * @mbg.generated Sun Mar 08 20:59:38 CST 2020
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.id
     *
     * @return the value of notice.id
     *
     * @mbg.generated Sun Mar 08 20:59:38 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.id
     *
     * @param id the value for notice.id
     *
     * @mbg.generated Sun Mar 08 20:59:38 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.notofier
     *
     * @return the value of notice.notofier
     *
     * @mbg.generated Sun Mar 08 20:59:38 CST 2020
     */
    public Integer getNotofier() {
        return notofier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.notofier
     *
     * @param notofier the value for notice.notofier
     *
     * @mbg.generated Sun Mar 08 20:59:38 CST 2020
     */
    public void setNotofier(Integer notofier) {
        this.notofier = notofier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.receiver
     *
     * @return the value of notice.receiver
     *
     * @mbg.generated Sun Mar 08 20:59:38 CST 2020
     */
    public Integer getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.receiver
     *
     * @param receiver the value for notice.receiver
     *
     * @mbg.generated Sun Mar 08 20:59:38 CST 2020
     */
    public void setReceiver(Integer receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.type
     *
     * @return the value of notice.type
     *
     * @mbg.generated Sun Mar 08 20:59:38 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.type
     *
     * @param type the value for notice.type
     *
     * @mbg.generated Sun Mar 08 20:59:38 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.outerId
     *
     * @return the value of notice.outerId
     *
     * @mbg.generated Sun Mar 08 20:59:38 CST 2020
     */
    public Integer getOuterid() {
        return outerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.outerId
     *
     * @param outerid the value for notice.outerId
     *
     * @mbg.generated Sun Mar 08 20:59:38 CST 2020
     */
    public void setOuterid(Integer outerid) {
        this.outerid = outerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.gmt_create
     *
     * @return the value of notice.gmt_create
     *
     * @mbg.generated Sun Mar 08 20:59:38 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.gmt_create
     *
     * @param gmtCreate the value for notice.gmt_create
     *
     * @mbg.generated Sun Mar 08 20:59:38 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.status
     *
     * @return the value of notice.status
     *
     * @mbg.generated Sun Mar 08 20:59:38 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.status
     *
     * @param status the value for notice.status
     *
     * @mbg.generated Sun Mar 08 20:59:38 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.title
     *
     * @return the value of notice.title
     *
     * @mbg.generated Sun Mar 08 20:59:38 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.title
     *
     * @param title the value for notice.title
     *
     * @mbg.generated Sun Mar 08 20:59:38 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }
}